include:
  - project: 'wpify/gitlab-ci-templates'
    ref: master
    file:
      - 'jobs/node.yml'
      - 'jobs/composer.yml'
      - 'jobs/tools.yml'

assets:
  stage: .pre
  extends: .node
  image: node:18
  artifacts:
    paths:
      - $CI_PROJECT_DIR/web/app/mu-plugins/$PLUGIN_SLUG/build
      - $CI_PROJECT_DIR/web/app/themes/$THEME_SLUG/style.css
      - $CI_PROJECT_DIR/web/app/themes/$THEME_SLUG/editor-style.css
    expire_in: 1 week

composer:
  stage: .pre
  extends: .composer_install
  artifacts:
    paths:
      - $CI_PROJECT_DIR/deps
      - $CI_PROJECT_DIR/vendor
      - $CI_PROJECT_DIR/web/app/mu-plugins
      - $CI_PROJECT_DIR/web/app/plugins
      - $CI_PROJECT_DIR/web/app/themes
      - $CI_PROJECT_DIR/web/app/vendor
      - $CI_PROJECT_DIR/web/wp
    expire_in: 1 week

deploy:
  stage: deploy
  extends: .tools
  environment:
    name: $ENV_NAME
    url: $ENV_URL
  needs:
    - assets
    - composer
  script: |
    replace "WPIFY_VERSION" "$CI_COMMIT_REF_NAME" \
      "web/app/mu-plugins/$PLUGIN_SLUG/$PLUGIN_SLUG.php" \
      "web/app/themes/$THEME_SLUG/style.css"

    server_deploy \
      .gitlab-ci/scripts/ \
      wp-cli.yml \
      assets/ \
      config/ \
      src/ \
      vendor/ \
      web/*.php \
      web/app/mu-plugins/ \
      web/app/plugins/ \
      web/app/themes/ \
      web/app/vendor/ \
      web/wp/*.php \
      web/wp/wp-admin/ \
      web/wp/wp-includes/
    
    server_run "$SERVER_PATH/.gitlab-ci/scripts/server-deploy $SERVER_PATH"
